common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('projecthome', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),


]

customer/urls.py
from django.urls import path
from . import views
app_name='customer'
urlpatterns=[
    path('customer_home',views.customer_home,name='home'),
    path('ccheckout',views.customer_checkout,name='checkout'),
    path('cmycart',views.customer_mycart,name='mycart'),
    path('cchangepassword',views.customer_changepassword,name='changepassword'),
    path('cproductdetails',views.customer_productdetails,name='productdetails'),
    path('cprofile',views.customer_profile,name='customer_profile'),
    path('cmyorders',views.customer_myorders,name='myorders'),
    path('cbaabtrawebsite',views.customer_Baabtrawebsite,name='Baabtra website'),
    path('cbootstrap',views.customer_Bootstrap,name='Bootstrap'),
    path('cbootstrapgrid',views.customer_Bootstrapgrid,name='bootstrapgrid'),
    path('cjavascripttest',views.customer_Javascripttest,name='javascripttest'),
    path('cvariable',views.customer_variable,name='variable'),
    path('cdomsample',views.customer_domsample,name='domsample'),
    path('cToDo',views.customer_ToDo,name='ToDo'),
    path('cProductDetail',views.customer_ProductDetail,name='Productdetail'),
    path('cjquerysample',views.customer_jquerysample,name='jquerysample'),
    path('cjquerysample2',views.customer_jquerysample2,name='jquerysample2'),
    path('cjquerysample2',views.customer_jquerysample2,name='jquerysample2'),
    path('cformname',views.customer_formname,name='formname'),
    path('clistsample',views.customer_listsample,name='listsample'),
    path('carraysample',views.customer_arraysample,name='arraysample'),
    path('cinnerwidthsample',views.customer_innerwidthsample,name='innerwidthsample'),
    path('cjqueryvalidation',views.customer_jqueryvalidation,name='jqueryvalidation'),
    path('cminitodolist',views.customer_minitodolist,name='minitodolist'),
    path('ccustomerregistration',views.customer_customerregistration,name='customerregistration'),
    path('ccssgrid',views.customer_cssgrid,name='cssgrid'),
    path('css_broto_sample',views.css_broto_sample,name='css_broto_sample'),


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),    

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

customer/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.shortcuts import render


def customer_home(request):
    return render(request,'customer/customer_home.html')

def customer_checkout(request):
    return render(request,'customer/checkout.html')

def customer_mycart(request):
    return render(request,'customer/my cart.html')

def customer_myorders(request):
    return render(request,'customer/my orders.html')

def customer_productdetails(request):
    return render(request,'customer/product details.html')

def customer_changepassword(request):
    return render(request,'customer/change password.html')

def customer_profile(request):
    return render(request, 'customer/customer_profile.html',{'customer_profile':customer_profile}) 

def customer_Baabtrawebsite(request):
    return render(request,'customer/Baabtra website.html') 

def customer_Bootstrap(request):
    return render(request,'customer/Bootstrap.html') 

def customer_Bootstrapgrid(request):
    return render(request,'customer/bootstrapgrid.html') 

def customer_Javascripttest(request):
    return render(request,'customer/javascripttest.html') 

def customer_variable(request):
    return render(request,'customer/variable.html') 

def customer_domsample(request):
    return render(request,'customer/domsample.html') 

def customer_ToDo(request):
    return render(request,'customer/ToDo.html') 

def customer_ProductDetail(request):
    return render(request,'customer/ProductDetail.html') 

def customer_jquerysample(request):
    return render(request,'customer/jquerysample.html') 

def customer_jquerysample2(request):
    return render(request,'customer/jquerysample2.html') 

def customer_formname(request):
    return render(request,'customer/formname.html') 

def customer_listsample(request):
    return render(request,'customer/listsample.html') 

def customer_arraysample(request):
    return render(request,'customer/arraysample.html') 

def customer_innerwidthsample(request):
    return render(request,'customer/innerwidthsample.html') 

def customer_jqueryvalidation(request):
    return render(request,'customer/jqueryvalidation.html')

def customer_minitodolist(request):
    return render(request,'customer/MiniToDoList.html') 

def customer_customerregistration(request):
    return render(request,'customer/customerregistration.html') 

def customer_cssgrid(request):
    return render(request,'customer/cssgrid.html') 

def css_broto_sample(request):
    return render(request,'customer/css_broto_sample.html') 

customer/templates/customer/Bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'style/bootstrapstyle.css' %}">
</head>

<body>
  <nav class="navbar navbar-expand-lg bg-primary text-center">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Welcome!!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" id="dropdownid">
              <li><a class="dropdown-item" href="#">New Arrivals</a></li>
              <li><a class="dropdown-item" href="#">Discount Offers</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="#">Most Demanded Products</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link">Contact Us</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Any Doubts...?" aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <div class="container"><br>


    <!-- Button trigger modal -->
    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">This is test for Modal</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Here is the space for the body of the modal
            here you can type the matter you want
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>
  </div><br>
  <div class="container">
    <div class="row">
      <div class="col-6 bg-danger mt-3 text-white text-center">6</div>
      <div class="col-6 bg-dark mt-3 text-white text-center">6</div>
      <div class="col-5 bg-success mt-3 text-white text-center">5</div>
      <div class="col-7 bg-warning mt-3 text-white text-center">7</div>
      <div class="col-4 bg-danger mt-3 text-white text-center">4</div>
      <div class="col-8 bg-dark mt-3 text-white text-center">8</div>
      <div class="col-3 bg-danger mt-3 text-white text-center">3</div>
      <div class="col-9 bg-secondary mt-3 text-white text-center">9</div>
      <div class="col-2 bg-danger mt-3 text-white text-center">2</div>
      <div class="col-10 bg-warning mt-3 text-white text-center">10</div>
      <div class="col-1 bg-dark mt-3 text-white text-center">1</div>
      <div class="col-11 bg-primary mt-3 text-white text-center">11</div>


    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
    integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
    crossorigin="anonymous"></script>
</body>

</html>

customer/templates/customer/bootstrapgrid.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/Bootstrapgridstyle.css' %}">
    <!-- <style
    .color{
        background-color: red;
    }
</style> -->
</head>

<body>
    <!-- <div class="container">
        <div class="row">
            <div class="col-lg-2 color">1</div>
            <div class="col-lg-2">2</div>
            <div class="col-lg-2 color">3</div>
            <div class="col-lg-2">4</div>
            <div class="col-lg-2 color">5</div>
            <div class="col-lg-2">6</div>
        </div>
    </div> --> 

    <!-- <div class="row">
        <div class="col-lg-4">
            <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt optio, ratione suscipit
                quod.</h2>
        </div>


        <div class="col-lg-8">
            <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id minus iusto eaque odio, itaque
                omnis
                amet vel a delectus ex culpa? Excepturi quae pariatur impedit minima dolore? Impedit, in
                tempore.</h2>
        </div>

    </div> -->

    <!-- <div class="row">
        <div class="col-lg-6">
            <h3>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet, alias praesentium. At
                soluta debitis aliquid aut quos autem, atque, quasi doloremque dolores ipsa praesentium
                alias quibusdam ex nostrum incidunt facere?</h3>
        </div>
        <div class="col-lg-6">
            <h3>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur maiores, nobis minus
                officia consectetur quas facilis eaque. Distinctio atque reprehenderit nisi, neque ea nulla,
                perferendis magnam voluptatibus quo culpa pariatur.</h3>
        </div>
    </div> -->
    <!-- <table class="table table-primary">
        <thead>
            <tr class="table-secondary">
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            <tr class="table-danger">
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
            </tr>
            <tr class="table-primary">
                <th scope="row">2</th>
                <td>Jacob</td>
                <td>Thornton</td>
                <td>@fat</td>
            </tr>
            <tr class="table-danger">
                <th scope="row">3</th>
                <td colspan="2">Larry the Bird</td>
                <td>@twitter</td>
            </tr>
        </tbody>
    </table>  -->
    <!-- <p>
        <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
            aria-controls="collapseExample">
            Link with href
        </a>
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample"
            aria-expanded="false" aria-controls="collapseExample">
            Button with data-bs-target
        </button>
    </p> -->
    <!-- <div class="collapse" id="collapseExample">
        <div class="card card-body">
            Some placeholder content for the collapse component. This panel is hidden by default but revealed when
            the
            user activates the relevant trigger.
        </div>
    </div> -->
    <!-- Example split danger button -->
    <!-- <div class="btn-group">
        <button type="button" class="btn btn-danger">Action</button>
        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
            aria-expanded="false">
            <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#">Separated link</a></li>
        </ul>
    </div> -->
    <!-- <nav aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav> -->
    <!-- <div class="card">
    <img src="..." class="card-img-top" alt="...">
  
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div> -->

    <!-- <div class="card" aria-hidden="true">
    <img src="..." class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title placeholder-glow">
        <span class="placeholder col-6"></span>
      </h5>
      <p class="card-text placeholder-glow">
        <span class="placeholder col-7"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-4"></span>
        <span class="placeholder col-6"></span>
        <span class="placeholder col-8"></span>
      </p>
      <a href="#" tabindex="-1" class="btn btn-primary disabled placeholder col-6"></a>
    </div>
  </div> -->
    <!-- <span class="placeholder col-12"></span>

        
<span class="placeholder col-12 bg-primary"></span>
<span class="placeholder col-12 bg-secondary"></span>
<span class="placeholder col-12 bg-success"></span>
<span class="placeholder col-12 bg-danger"></span>
<span class="placeholder col-12 bg-warning"></span>
<span class="placeholder col-12 bg-info"></span>
<span class="placeholder col-12 bg-light"></span>
<span class="placeholder col-12 bg-dark"></span> -->
    <!-- Your result will be exhibited in a short time <br>
<div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div> -->
    <!-- <button type="button" class="btn btn-primary" id="liveToastBtn">Show live toast</button>

    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <img src="..." class="rounded me-2" alt="...">
                <strong class="me-auto">Bootstrap</strong>
                <small>11 mins ago</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                Hello, world! This is a toast message.
            </div>
        </div>
    </div> -->

    <!-- <script>
        const toastTrigger = document.getElementById('liveToastBtn')
        const toastLiveExample = document.getElementById('liveToast')
        if (toastTrigger) {
            toastTrigger.addEventListener('click', () => {
                const toast = new bootstrap.Toast(toastLiveExample)

                toast.show()
            })
        }
    </script> <br><br>
    <button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top"
        data-bs-custom-class="custom-tooltip" data-bs-title="This top tooltip is themed via CSS variables.">
        Custom tooltip
    </button>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
        integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
        crossorigin="anonymous"></script> -->






    <!-- test for bootstrapgrid -->
    <div class="container">
        <h2>Vertical or Basic form</h2>
        <form role="form">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="" id="name" placeholder="Enter The Name">
            </div><br>
            <button class="btn  btn-primary btn-block" type="submit"> Sign In</button>
        </form>
    </div>
</body>

</html>

customer/templates/customer/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is the checkout section
</body>
</html>

customer/templates/customer/css_broto_sample.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style/css_broto_sample.css'  %}">
</head>

<body>
    <h1 class="sample">
        hai welcome to my page
    </h1>
    <h2 class="sample">
        this is a test for testing exteranl css
    </h2>
    <div class="maindiv">
        <p>something</p>
    </div>
</body>

</html>

customer/templates/customer/cssgrid.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grid Example</title>
    <link rel="stylesheet" href="{% static 'style/cssgridstyle.css' %}">
</head>

<body>
    <div class="grid-container">
        <!-- <div class="grid-item grid-item-1"></div>
        <div class="grid-item grid-item-2"></div>
        <div class="grid-item grid-item-3"></div> -->
        <div class="item1">hai</div>
        <div class="item2">hello</div>
        <div class="item3">good afternoon</div>
        <div class="item4">good to c u</div>

    </div>

</body>

</html>

customer/templates/customer/customer_profile.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>Customer Profile</title>
{% endblock %}

{% block content %}

<div class="container" style="display: grid;  justify-content: center;">
    <h1><B><U>CUSTOMER PROFILE</U></B></h1>
    <div>
        <label for="inputEmail4" class="form-label">Name</label>
        <input type="text" class="form-control" id="inputEmail4" style="width: 400px;" name="customer_name" value="{{customer_profile.name}}">
    </div>
    <div>
        <label for="inputPassword4" class="form-label">Mobile Number</label>
        <input type="text" class="form-control" id="inputPassword4" style="width: 400px;" name="customer_mobile" value="{{customer_profile.mobile_number}}">
    </div>
    <div>
        <label for="inputEmail4" class="form-label">Email</label>
        <input type="text" class="form-control" id="inputEmail4" style="width: 400px;" name="customer_phone" value="{{customer_profile.email}}">
    </div><br>
</div>
{% endblock %}

customer/templates/customer/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to my home page </h1>
    <img src="{% static 'images/image1.jpg' %}" alt="">
    <a href="{% url 'customer:productdetails' %}">abcd</a>
</body>
</html>

customer/templates/customer/innerwidthsample.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body>
    <!-- <div id="new" style="border: 2px red solid; width: 100px; height: 100px; padding: 10px; margin: 10px;">
        Hai Welcome to my page
    </div>
    <script>
        console.log($("#new").innerHeight())
    </script> -->
    <p>hello</p>
    <p>hiii</p>
    <p>hooi</p>
    <div>
        <ul>
            <li>yahya</li>
            <li>vishnu</li>
            <li>aparna</li>
            <li><span>prashob</span></li>
        </ul>
    </div>
    <script>
        $(document).ready(function(){
            console.log($("p").eq(0))
        })
    </script>
</body>

</html>

customer/templates/customer/jquerysample2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul id="ul">
        <li>python</li>
        <li>java</li>
        <li>c++</li>
        <li>.net</li>
    </ul>
    <p>programming language</p>
    <script>
        $(document).ready(function(){
        $('#ul').empty()
        $('#ul').remove()

        })
    </script>
</body>
</html>

customer/templates/customer/master_customer.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    {% block title %}
    <title>Master Customer</title>
    {% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="#">Shop-E-huB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'customer:home' %}"
                            style="color: white;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:mycart' %}" style="color: white;">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:customer_profile' %}" style="color: white;">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:myorders' %}" style="color: white;">Orders</a>
                    </li>
                </ul>
                <div class="dropdown">
                    <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        All categories
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Men</a></li>
                        <li><a class="dropdown-item" href="#">Women</a></li>
                        <li><a class="dropdown-item" href="#">Kids</a></li>
                    </ul>
                </div> &nbsp;&nbsp;
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search a Product" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light" style="padding-left: 40px;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:changepassword' %}" style="color: white;">Change
                            Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'common:customer_login' %}" style="color: white;">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}


    {% endblock %}
</body>

</html>

customer/templates/customer/my orders.html
{% extends 'customer/master_customer.html' %}
{% load static %}

{% block title %}
<title>My Orders</title>
{% endblock %}

{% block content %}
<br>
<h1>My Orders</h1>

{% endblock %}