common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('projecthome', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),    

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path
from . import views
app_name='seller'


urlpatterns=[
    path('addproduct',views.add_product,name='add_product'),
    path('changepassword',views.change_password,name='changepassword'),
    path('sellerhome',views.seller_home,name='seller_home'),
    path('productcatalogue',views.product_catalogue),
    path('sellerprofile',views.seller_profile,name='seller_profile'),
    path('updatestock',views.update_stock,name='update_stock'),
    path('vieworders',views.view_orders),
    path('javascriptsample',views.javascript_sample),
    path('master_seller',views.master_seller,name='master_seller'),
    path('view_product',views.view_product,name='view_product')


]

seller/models.py
from django.db import models
# Create your models here.

# class Product(models.Model):
#     seller = models.ForeignKey(Seller, on_delete = models.CASCADE)
#     product_name = models.CharField(max_length=50)
#     product_description = models.CharField(max_length=100)
#     product_category = models.CharField(max_length=50)
#     product_no = models.BigIntegerField()
#     product_stock = models.IntegerField()
#     product_price = models.IntegerField()
#     product_image = models.ImageField(upload_to = 'product/')
    
#     class Meta:
#         db_table = 'product_tb'

seller/views.py
from django.shortcuts import render


def add_product(request):
    return render(request, 'seller/add product.html')


def change_password(request):
    return render(request, 'seller/change password.html')


def seller_home(request):
    return render(request, 'seller/seller home.html')


def product_catalogue(request):
    return render(request, 'seller/product catalogue.html')


def seller_profile(request):
    return render(request, 'seller/seller profile.html')


def update_stock(request):
    return render(request, 'seller/update stock.html')

def view_product(request):
    return render(request, 'seller/view_product.html')


def view_orders(request):
    return render(request, 'seller/view orders.html')

def javascript_sample(request):
    return render(request, 'seller/javascriptsample.html')

def master_seller(request):
    return render(request, 'seller/master_seller.html')

seller/templates/seller/add product.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Add Product</title>
{% endblock %}

{% block content %}
<h1
    style="text-align: center; color: rgb(50, 50, 134); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-size: 30px;margin-top: 20px;">
    <u>ADD PRODUCT </u>
</h1><br>
<div class="container"
    style="background-color: rgb(147, 228, 147); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;height: 650px; width: 400px;border-radius: 10px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Name</label>
            <input type="text" class="form-control" id="nameField" name="p_name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Product Description</label>
            <textarea class="form-control" id="descriptionField" rows="1" name="p_description"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Category</label>
            <input type="text" class="form-control" id="categoryField" name="p_category">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Product Number</label>
            <input type="text" class="form-control" id="numberField" name="p_no">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Current Stock</label>
            <input type="text" class="form-control" id="stockField" name="p_stock">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Price</label>
            <input type="text" class="form-control" id="priceField" name="p_price">
        </div>
        <label for="exampleFormControlInput1" class="form-label">Product Image</label>
        <div class="input-group mb-3">
            <input type="FILE" class="form-control" id="inputGroupFile02" name="p_image">
            <label class="input-group-text" for="inputGroupFile02">Upload</label>
        </div>
        <button type="submit" class="btn btn-success">Submit Product</button>
    </form>
</div>
<br>
{% endblock %}

seller/templates/seller/change password.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Change Password</title>
{% endblock %}

{% block content %}
<h1
    style="text-align: center; color: rgb(50, 50, 134); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-size: 30px;margin-top: 20px;">
    <u>CHANGE PASSWORD </u>
</h1><br>
<div class="container"
    style="background-color: rgb(147, 228, 147); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;height: 350px; width: 400px;border-radius: 10px;">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">old password</label>
            <input type="password" class="form-control" name="old_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">new password</label>
            <input type="password" class="form-control" name="new_password">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">confirm Password</label>
            <input type="password" class="form-control" name="confirm_password">
        </div>

        <button type="submit" class="btn btn-success">Change password</button>
        {{ error }} {{ success }}
    </form>
</div>
{% endblock %}

seller/templates/seller/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is the home page for seller
    
</body>
</html>

seller/templates/seller/javascriptsample.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- <h1 id="test">This is a test</h1>
    <p class="p_class1">
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquam magni minima reprehenderit sequi amet, iste
        non earum totam soluta aut quaerat eaque labore necessitatibus atque possimus est at ducimus maiores?
    </p>
    <p class="p_class1">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos ea suscipit officia quisquam eius dicta et omnis
        laboriosam quidem culpa obcaecati mollitia laudantium, voluptas vero sed minima! Maxime, natus tenetur.
    </p> -->

    <!-- <input type="button" onclick="change()" value="Click Me"> -->
    <!-- <input type="text" id="num1"><br><br>
    <input type="text" id="num2"><br><br>
    <button onclick="sum()">Answer</button><br><br>
    <input type="text" id="answer"> -->
    <label for="">Enter The First Number</label>
    <input type="text" id="num1"><br><br>
    <label for="">Select the Operation</label> &nbsp;
     <select name="" id="select">
        <option value="+">+</option>
        <option value="-">-</option>
        <option value="*">*</option>
        <option value="/">/</option>
    </select> <br><br>
     <label for="">Enter The Second Number</label>
    <input type="text" id="num2"><br><br>
    <button onclick="answer()">Show Result</button> <br><br>
    <label for="">Your Result is</label>
    <input type="text" id="result"><br><br>
    <select name="" id="fruit" >
        <option value="apple">apple</option>
        <option value="orange">orange</option>
        <option value="mango">mango</option>
        <option value="lemon">lemon</option>
    </select><br><br>
    <button onclick="delete_option()">delete</button>  
   <!-- <input type="password" id="password">
   <button onclick="show()">show password</button> -->
    <script>
        // h = document.getElementById('test')
        // console.log(h)
        // var1 = document.getElementsByTagName('p')
        // console.log(var1[1])
        // a1 = document.getElementsByClassName('p_class1')
        // console.log(a1)
        // function change() {
        //     h.innerHTML = "Hello Welcome"
        // }
        // function sum() {
        //    num1 = document.getElementById('num1').value
        //    num2 = document.getElementById('num2').value
        //    result =  parseInt(num1) + parseInt(num2)
        //    document.getElementById('answer').value = result
        // }

        // function answer() {
        //     num1 = document.getElementById('num1').value
        //     num2 = document.getElementById('num2').value
        //     a = document.getElementById('select').value
        //     if (a == '+'){
        //         document.getElementById('result').value = parseInt(num1) + parseInt(num2)
        //     }else if (a == '-'){
        //         document.getElementById('result').value = parseInt(num1) - parseInt(num2)
        //     }else if (a == '*'){
        //         document.getElementById('result').value = parseInt(num1) * parseInt(num2)
        //     }else {
        //         document.getElementById('result').value = parseInt(num1) / parseInt(num2)
        //     }
           
        // }
        // document.getElementById('result').style.color = 'red'
        // function show(){
        //     document.getElementById('password').type = 'text'
        // }
        function delete_option(){
            x = document.getElementById('fruit')
                x.remove(x.selectedIndex)
            }
        
    </script>
</body>

</html>

seller/templates/seller/master_seller.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    {% block title %}
    <title>Master seller</title>
    {% endblock %}
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="#"
                style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"><i>Shop-E-huB</i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'seller:seller_home' %}"
                            style="color: white;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:add_product' %}" style="color: white;">Add Product</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:update_stock' %}" style="color: white;">Update
                            Stock</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:seller_profile' %}" style="color: white;">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:view_product' %}" style="color: white;">View Products</a>
                    </li>
                </ul>

                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light" style="padding-left: 40px;">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'seller:changepassword' %}" style="color: white;">Change
                            Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'common:seller_login' %}" style="color: white;">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

seller/templates/seller/product catalogue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is the page for viewing the catalogues of the products
</body>
</html>

seller/templates/seller/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    this is the page for viewing the profile section for the seller
    
</body>
</html>

seller/templates/seller/seller home.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Seller Home</title>
{% endblock %}

{% block content %}
<div class="maindiv" style="display: inline-flex;">
    <div class="image_div" style="margin-left: 200px;">
        <img src="{% static 'images/standing_man.png' %}" height="500px" width="400px" alt="" class="imagediv2">
    </div>
    <div class="sale_main_heading" style="margin-top: 140px;">
        <div class="sale_heading">
            <h6><i>New Year's Sale</i></h6>
        </div>
        <div class="yahyasample">
            <h1>Men's Clothing</h1>
        </div>
        <h4>UP TO 50% OFF</h4>
        <button class="btn btn-warning" type="submit"> <b>Shop Now !!</b></button>
    </div>
</div>
{% endblock %}

seller/templates/seller/seller profile.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Seller Profile</title>
{% endblock %}

{% block content %}
<div class="container" style="display: grid;  justify-content: center;">
    <h1 style="color: rgb(91, 48, 84);">
        <b><u>SELLER PROFILE</u></b>
    </h1><br>
    <img src="{{ seller_profile.seller_pic.url }}" alt="" width="200px">
    <div style="display: flex;">
        <label for="inputEmail4" class="form-label">Name</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your Name" style="width: 400px;"
            value="{{ seller_profile.name }}">
    </div><br>
    <div style="display: flex;">
        <label for="inputPassword4" class="form-label">Email Address</label>&nbsp;&nbsp;&nbsp;&nbsp;
        <input type="email" class="form-control" id="inputPassword4" placeholder="Enter your Email"
            style="width: 400px;" value="{{ seller_profile.email }}">
    </div><br>
    <div style="display: flex;">
        <label for="inputEmail4" class="form-label">Phone Number</label>&nbsp;&nbsp;&nbsp;
        <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your Phone Number"
            style="width: 400px;" value="{{ seller_profile.mobile_number }}">
    </div>
</div>
{% endblock %}

seller/templates/seller/update stock.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>Update Stock</title>
{% endblock %}

{% block content %}
<h1
    style="text-align: center; color: rgb(50, 91, 134); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;font-size: 30px;margin-top: 20px;">
    <u>UPDATE STOCK</u>
</h1><br>
<div class="container"
    style="background-color: rgb(147, 186, 228); font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;height: 400px; width: 400px;border-radius: 10px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Select Category</label>
            <input type="email" class="form-control" id="nameField" name="p_name">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Product No</label>
            <textarea class="form-control" id="descriptionField" rows="1" name="p_description"></textarea>
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Current Stock</label>
            <input type="text" class="form-control" id="categoryField" name="p_category">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">New Stock</label>
            <input type="text" class="form-control" id="categoryField" name="p_no">
        </div>
        <button type="submit" class="btn btn-danger">Update</button>
    </form>
</div>
{% endblock %}

seller/templates/seller/view_product.html
{% extends 'seller/master_seller.html' %}
{% load static %}

{% block title %}
<title>View Product</title>
{% endblock %}

{% block content %}
<br><br>

<div class="card mb-3" style="max-width: 450px;">
    <div class="row g-0">
        {% for product in products %}
        <div class="col-md-4">
            <img src="{{ product.product_image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            
            <div class="card-body">
                <h5 class="card-title">Jack & Jones</h5>
                <p class="card-text">Men Blue Long Sleeves Casual Shirt</p>
                <label for="">Quantity</label>
                <input type="text" style="width: 30px; height: 20px;"><br>
                <label for="">Total Price</label>
                <input type="text" style="width: 30px; height: 20px;"><br>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-success">Save for later</button>
                    <button type="button" class="btn btn-danger">Remove</button>
                </div>
            </div>
            
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}