common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns = [
    path('comadminlogin', views.admin_login, name='admin_login'),
    path('customerlogin', views.customer_login, name='customer_login'),
    path('customersignup', views.customer_signup, name='customer_signup'),
    path('projecthome', views.project_home, name='project_home'),
    path('sellerlogin', views.seller_login, name='seller_login'),
    path('sellersignup', views.seller_signup, name='seller_signup'),
    path('mastercommon', views.master_common, name='master_common'),
    path('test', views.test, name='test'),


]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customer.urls')),
    path('common/', include('common.urls')),
    path('ecom_admin/', include('ecom_admin.urls')),
    path('seller/', include('seller.urls')),    

]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

# class Customers(models.Model):
#     name = models.CharField(max_length=50)
#     mobile_number = models.CharField(max_length=20)
#     email = models.CharField(max_length=30)
#     password = models.CharField(max_length=20)
    
#     class Meta: 
#         db_table = 'customer_tb'


# class Seller(models.Model):
#     name = models.CharField(max_length=50) 
#     mobile_number = models.BigIntegerField()
#     email = models.CharField(max_length=30)
#     password = models.CharField(max_length=20)
#     user_name = models.IntegerField(default=0)
#     bank_name = models.CharField(max_length=30)
#     bank_branch = models.CharField(max_length=40)
#     ifsc_code = models.CharField(max_length=20)
#     seller_pic = models.ImageField(upload_to='seller/')

#     class Meta:
#         db_table = 'seller_tb'

class Customer(models.Model) :
    c_name = models.CharField(max_length = 50)
    c_email = models.CharField(max_length = 50)
    c_address = models.CharField(max_length = 100)
    c_mobile = models.BigIntegerField()
    c_gender = models.CharField(max_length = 10)
    c_password = models.CharField(max_length = 30, default = '')
    c_status = models.CharField(max_length = 25, default = 'active')
        
    class Meta : 
        db_table = 'customer'

class Seller(models.Model) :
    s_name = models.CharField(max_length = 50)
    s_email = models.CharField(max_length = 50)
    s_address = models.CharField(max_length = 100)
    s_mobile = models.BigIntegerField()
    s_username = models.IntegerField(default = 0)
    s_password = models.CharField(max_length = 50)
    s_bank_name = models.CharField(max_length = 50)
    s_bank_branch = models.CharField(max_length = 50)
    s_ifsc_code = models.CharField(max_length = 50)
    s_acc_number = models.BigIntegerField()
    s_image = models.ImageField(upload_to = 'seller/')
    s_status = models.CharField(max_length = 20, default = 'pending')

    class Meta : 
        db_table = 'seller'

    

common/views.py
from django.conf import settings
from django.shortcuts import render,redirect
from random import randint
from .models import Customer, Seller
from django.core.mail import send_mail


def admin_login(request):
    return render(request, 'common/admin login.html')


def customer_login(request):

    msg = ''
    if request.method == 'POST':
        cemail = request.POST['email']
        cpassword = request.POST['password']
        try :
            customer = Customer.objects.get(c_email = cemail,c_password = cpassword)
            request.session['customer'] = customer.id
            return redirect('customer:home')

        except:
            msg = 'invalid credentials'
    
    return render(request, 'common/customer login.html',{'message':msg})


def customer_signup(request):
    msg = ''

    if request.method == 'POST' :
        cname = request.POST['customer_name']
        cemail = request.POST['email']
        cmobile = request.POST['mobile_number']
        caddress = request.POST['address']
        cgender = request.POST['gender']
        cpassword = request.POST['password']

        try:
            new_customer = Customer(
                c_name = cname, 
                c_email = cemail, 
                c_mobile = cmobile,
                c_address = caddress, 
                c_gender = cgender,
                c_password = cpassword
                )
            new_customer.save()
            msg = 'successfully registered'
        except:
            msg = 'invalid credentials'


    return render(request, 'common/customer signup.html', {'message':msg})


def project_home(request):
    return render(request, 'common/project home.html')


def seller_login(request):
    msg = ''

    if request.method == 'POST' :

        susername = request.POST['username']
        spassword = request.POST['password']
        try:
            seller = Seller.objects.get(s_username=susername, s_password = spassword)
            return redirect('seller:seller_home')
        except:
            msg = 'Invalid Credentials'
    return render(request, 'common/seller login.html',{'message':msg})


def seller_signup(request):
    msg = ''
    if request.method == 'POST' :
        sname = request.POST['seller_name']
        smobile = request.POST['seller_mobile']
        semail = request.POST['seller_email']
        saddress = request.POST['seller_address']
        sbankname = request.POST['seller_bank_name']
        saccountnumb = request.POST['seller_account_number']
        sbankbranch = request.POST['seller_bank_branch']
        sifsccode = request.POST['seller_ifsc']
        simage = request.FILES['seller_pic']
        susername = randint(1000,9999)
        spassword = 'sel-'+sname.lower()+str(susername)

        seller = Seller(
            s_name = sname,
            s_mobile = smobile,
            s_email = semail,
            s_address = saddress,
            s_bank_name = sbankname,
            s_acc_number = saccountnumb,
            s_bank_branch = sbankbranch,
            s_ifsc_code = sifsccode,
            s_image = simage,
            s_username = susername,
            s_password = spassword)
        seller.save()
        
        msg = 'seller registered successfully'

        subject = 'account name and password'
        message = 'hai your username is '+str(susername)+'and your password is '+spassword
        email_from = settings.EMAIL_HOST_USER
        send_mail(
            subject,
            message,
            email_from,
            [semail],
            fail_silently = False
        )
        
    return render(request, 'common/seller signup.html',{'message':msg})

def master_common(request):
    return render(request, 'common/master_common.html')         

def test(request):
    return render(request, 'common/test.html')

    

     

common/templates/common/admin login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
</head>
<body>
    <h1>admin login</h1>
</body>
</html>

common/templates/common/broto_fb_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style/fb.css' %}">
    <title>facebook signup</title>
</head>

<body>
    <div class="container">
        <div class="header">
            <div class="logo">
                <!-- <a class="logo_text" href="{% url 'common:broto_fb_page' %}">facebook</a> -->
                <img src="{% static 'images/fb_logo.png' %}" alt="" height="80px" width="220px">
            </div>
            <div class="login">
                <table class="table_controls">
                    <tr>
                        <td>
                            <label for="">E-mail</label>
                        </td>
                        <td>
                            <label for="">Password</label>
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <input type="text">
                        </td>
                        <td>
                            <input type="password">
                        </td>
                        <td>
                            <button class="btn_class">
                                Log In
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>
                            Forgotten Account?
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="main_body"><br>
            <div class="left_body">
                <p class="para_class">
                    Facebook helps you connect and share with <br> the people in your life.
                </p>
            </div>
            <div class="right_body">
                <p>
                    asdsds
                </p>
            </div>
        </div>
    </div>
</body>

</html>

common/templates/common/customer login.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Customer Login</title>
{% endblock %}
{% block content %}
<div style="background-color: rgb(103, 103, 190)" ;>
    <div class="container" style="display: grid;  justify-content: center;">
        <h1 style="color: rgb(48, 48, 91);">
            <b><u>CUSTOMER LOGIN</u></b>
        </h1><br>
        <form method="POST">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="inputEmail4" class="form-label" style="color: white;">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Enter your E-mail Address"
                    style="width: 400px;" name="email">
            </div>
            <div>
                <label for="inputPassword4" class="form-label" style="color: white;">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Enter your Password"
                    style="width: 400px;" name="password">
            </div>
            <a href="{% url 'common:customer_signup' %}" style="color: white;">New to ShopEhuB?</a>
            <a href="#forgot_password" style="color: white;">Forgot Password?</a>
            <br>
            <div>
                <button type="submit" class="btn btn-success" a>Login</button>
            </div><br>
            <h6 style="color: white;">
                By continuing, you agree to Shop-E-huB's <br> <a href="#conditions_of_use"
                    style="color:rgb(227, 227, 27);">Conditions of Use</a> and <a href="#privacy_notice"
                    style="color:rgb(227, 227, 27);">Privacy Notice</a>
            </h6>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/customer signup.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Customer Registration</title>
{% endblock %}


{% block content %}
<div style="background-color: rgb(103, 178, 190);">
    <div class="container" style="display: grid;  justify-content: center;">
        <h1 style="color: rgb(48, 91, 91);">
            <b><u>CUSTOMER REGISTRATION</u></b>
        </h1>
        <form method="POST" style="display: grid;  justify-content: center;">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="input_name" style="color: white;">Your Name</label>
                <input type="text" class="form-control" id="cust_name" placeholder="Enter Your Name"
                    style="width: 400px;" name="customer_name">
            </div>
            <div>
                <label for="input_mobile" class="form-label" style="color: white;">Your Mobile Number</label>
                <input type="text" class="form-control" id="cust_mobile" placeholder="Enter Your Mobile Number"
                    style="width: 400px" name="mobile_number">
            </div>
            <div>
                <label for="input_mobile" class="form-label" style="color: white;">Address</label>
                <textarea name="address" class = "form-control" id="cust_address" cols="30" rows="3" style="width: 400px"></textarea>
            </div>
            <div>
                <label for="inputEmail4" class="form-label" style="color: white;">Email</label>
                <input type="email" class="form-control" id="cust_email" placeholder="Enter your E-mail Address"
                    style="width: 400px;" name="email">
            </div>
            <div>
                <label for="inputPassword4" class="form-label" style="color: white;">Password</label>
                <input type="password" class="form-control" id="cust_password" placeholder="Atleast 6 characters"
                    style="width: 400px;" name="password">
            </div>
            <div>
                <label for="inputPassword4" class="form-label" style="color: white;">Gender</label><br>
                <label for="male" style="color: rgb(203, 198, 198);">male</label>
                <input type="radio" id="male" name="gender" value="male">
                <label for="female" style="color: rgb(203, 198, 198);">female</label>
                <input type="radio" id="female" name="gender" value="female">
            </div>
            <br>
            <div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </div><br>
            <h6 style="color: white;">
                By enrolling your mobile phone number,you consent to <br> recieve automated security notifications
                via
                text <br> message from amazon.message and data <br> rates may apply.
            </h6>
        </form>
    </div>
</div>
<!-- <script>

    var cust_name = document.getElementById('cust_name');
    var cust_mobile = document.getElementById('cust_mobile').value;
    var cust_email = document.getElementById('cust_email').value;
    var cust_password = document.getElementById('cust_password').value;
    var s_name = document.getElementById('name_error_msg_id')

    function customer_validation() {



        if (cust_name.value == "") {                                                       //if nothing is entered in the email field
            s_name.innerHTML = "Username must be filled out"; //required error message is inserted to the particular input text
            document.getElementById('cust_name').style.border = '1px solid red';                      //to make the input field's border in to reddish colour
            return false;

        } 
        else{
            s_name.innerHTML = '';                           //since the condition is false the form gets submitted                      
            document.getElementById('cust_name').style.border = '';                      //to make the input field's border in to reddish colour


        }

        // if (cust_name.length < 8) {                                      //if nothing is entered in the email field

        //     document.getElementById('name_error_msg_id').innerHTML = "must be atleast 8 characters"; //required error message is inserted to the particular input text
        //     document.getElementById('cust_name').style.border =  '1px solid red';                      //to make the input field's border in to reddish colour
        //     return false;

        // } else {

        //     document.getElementById('name_error_msg_id').innerHTML = "";                           //since the condition is false the form gets submitted
        //     document.getElementById('cust_name').style.border = "";

        // }

    }

</script> -->
{% endblock %}

common/templates/common/master_common.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    {% block title %}
    <title>Master common</title>
    {% endblock %}



</head>

<body>
    <nav class="navbar navbar-expand-lg bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="#"
                style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
                <i>ShopEhuB</i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 text-light">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'common:project_home' %}" style="color: white;">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false" style="color: white;">
                            Registration
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'common:customer_signup' %}">Customer
                                    Registration</a></li>
                            <li><a class="dropdown-item" href="{% url 'common:seller_signup' %}">Seller Registration</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false" style="color: white;">
                            Login
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'common:customer_login' %}">Customer Login</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'common:seller_login' %}">Seller Login</a></li>
                        </ul>
                    </li>
                </ul>


                <div class="dropdown">
                    <button class="btn btn-warning dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        All categories
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Men</a></li>
                        <li><a class="dropdown-item" href="#">Women</a></li>
                        <li><a class="dropdown-item" href="#">Kids</a></li>
                    </ul>
                </div> &nbsp;&nbsp;
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search a Product" aria-label="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}


    {% endblock %}
</body>

</html>

common/templates/common/project home.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
        <title>Home</title>
{% endblock %}

{% block content %}

    <div class="maindiv" style="display: inline-flex;">
        <div class="image_div" style="margin-left: 200px;">
            <img src="{% static 'images/standing_man.png' %}" height="500px" width="400px" alt="" class="imagediv2">
        </div>
        <div class="sale_main_heading" style="margin-top: 140px;">
            <div class="sale_heading">
                <h6><i>New Year's Sale</i></h6>
            </div>
            <div class="yahyasample">
                <h1>Men's Clothing</h1>
            </div>
            <h4>UP TO 50% OFF</h4>
            <button class="btn btn-warning" type="submit"> <b>Shop Now !!</b></button>
        </div>
    </div>

    
{% endblock %}    

common/templates/common/seller login.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Seller Login</title>
{% endblock %}
{% block content %}



<div style="background-color: rgb(190, 103, 149);">


    <div class="container" style="display: grid;  justify-content: center;">
        <h1 style="color: rgb(91, 48, 84);">
            <b><u>SELLER LOGIN</u></b>
        </h1><br>
        <form action="" method="POST">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="inputEmail4" class="form-label" style="color: white;">User Name</label>
                <input type="text" class="form-control" id="inputEmail4" placeholder="Enter your User Name"
                    style="width: 400px;" name="username">
            </div>
            <div>
                <label for="inputPassword4" class="form-label" style="color: white;">Password</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Enter your Password"
                    style="width: 400px;" name="password">
            </div>
            <a href="{% url 'common:seller_signup' %}" style="color: white;">New to ShopEhuB?</a>
            <a href="#forgot_password" style="color: white;">Forgot Password?</a>
            <br>
            <div>
                <button type="submit" class="btn btn-warning text-light">Login</button>
            </div><br>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/seller signup.html
{% extends 'common/master_common.html' %}
{% load static %}
{% block title %}
<title>Seller Registration</title>
{% endblock %}


{% block content %}
<div style="background-color: rgb(190, 170, 103); ">
    <div class="container" style="display: grid;  justify-content: center;">
        <h1 style="color: rgb(91, 72, 48);">
            <b><u>SELLER REGISTRATION</u></b>
        </h1><br>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{message}}
            <div>
                <label for="input_name" style="color: white;">Your Name</label>
                <input type="text" class="form-control" id="input_name" placeholder="Enter Your Name"
                    style="width: 400px;" name="seller_name">
            </div>
            <div>
                <label for="input_mobile" class="form-label" style="color: white;">Your Mobile Number</label>
                <input type="number" class="form-control" id="input_mobile" placeholder="Enter Your Mobile Number"
                    style="width: 400px" name="seller_mobile" ;>
            </div>
            <div>
                <label for="inputEmail4" class="form-label" style="color: white;">Email</label>
                <input type="email" class="form-control" id="inputEmail" placeholder="Enter your E-mail Address"
                    style="width: 400px;" name="seller_email">
            </div>
            <div>
                <label for="inputEmail4" class="form-label" style="color: white;">address</label>
                <input type="text" class="form-control" id="inputEmail" placeholder="Enter your Address"
                    style="width: 400px;" name="seller_address">
            </div>
            <div>
                <label for="input_bank_name" style="color: white;">Bank Name</label>
                <input type="text" class="form-control" id="input_bank_name" placeholder="Enter Your Bank Name"
                    style="width: 400px;" name="seller_bank_name">
            </div>
            <div>
                <label for="acc_name" style="color: white;">Account Number</label>
                <input type="number" class="form-control" id="account_number" placeholder="Enter Your Account Number"
                    style="width: 400px;" name="seller_account_number">
            </div>
            <div>
                <label for="input_branch" class="form-label" style="color: white;">Bank Branch</label>
                <input type="text" class="form-control" id="input_branch" placeholder="Enter Your bank branch"
                    style="width: 400px" name="seller_bank_branch" ;>
            </div>
            <div>
                <label for="input_ifsc" class="form-label" style="color: white;">ifsc code</label>
                <input type="text" class="form-control" id="input_ifsc" placeholder="Enter Your ifsc code"
                    style="width: 400px" name="seller_ifsc">
            </div><br>
            <div class="input-group mb-3">
                <input type="file" class="form-control" id="inputGroupFile02" name="seller_pic">
                <label class="input-group-text" for="inputGroupFile02">Upload</label>
            </div>
            <br>
            <div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </div><br>
        </form>
    </div>
</div>
{% endblock %}

common/templates/common/test.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <title>Test</title>
</head>

<body>
    <div style="background-color: rgb(103, 178, 190); ">
        <div class="container" style="display: grid;  justify-content: center;">
            <h1 style="color: rgb(48, 91, 91);">
                <b><u>CUSTOMER REGISTRATION</u></b>
            </h1>
            <form action="" method="POST" style="display: grid;  justify-content: center;">
                {% csrf_token %}
                <div>
                    <label for="input_name" style="color: white;">Your Name</label>
                    <p id="name_error_msg_id" style="display: inline;color: red;"></p>
                    <input type="text" class="form-control" id="cust_name" placeholder="Enter Your Name"
                        style="width: 400px;" name="your_name">
                </div>
                <div>
                    <label for="input_mobile" class="form-label" style="color: white;">Your Mobile Number</label>
                    <input type="text" class="form-control" id="cust_mobile" placeholder="Enter Your Mobile Number"
                        style="width: 400px" name="mobile_number">
                </div>
                <div>
                    <label for="inputEmail4" class="form-label" style="color: white;">Email</label>
                    <input type="email" class="form-control" id="cust_email" placeholder="Enter your E-mail Address"
                        style="width: 400px;" name="email">
                </div>
                <div>
                    <label for="inputPassword4" class="form-label" style="color: white;">Password</label>
                    <input type="password" class="form-control" id="cust_password" placeholder="Atleast 6 characters"
                        style="width: 400px;" name="password">
                    <p id="empty_error_msg_id" style="display: inline; color: red;"></p>

                </div>
                <br>
                <div>
                    <button type="submit" class="btn btn-primary" onclick="return customer_validation()">Sign
                        Up</button>
                </div><br>

                <script>

                    var cust_name = document.getElementById('cust_name').value;
                    var cust_mobile = document.getElementById('cust_mobile').value;
                    var cust_email = document.getElementById('cust_email').value;
                    var cust_password = document.getElementById('cust_password').value;

                    function customer_validation() {



                        if (cust_name == "") {                                                          //if nothing is entered in the email field

                            document.getElementById('cust_name_error_msg_id').innerHTML = "Username must be filled out"; //required error message is inserted to the particular input text
                            document.getElementById('cust_name').style.border = '1px solid red';                      //to make the input field's border in to reddish colour
                            return false;

                        } else {

                            document.getElementById('cust_name_error_msg_id').innerHTML = "";                           //since the condition is false the form gets submitted                      
                            document.getElementById('cust_name').style.border = "";                      //to make the input field's border in to reddish colour


                        }

                        if (cust_name.length < 8) {                                      //if nothing is entered in the email field

                            document.getElementById('cust_name_error_msg_id').innerHTML = "must be atleast 8 characters"; //required error message is inserted to the particular input text
                            document.getElementById('cust_name').style.border = '1px solid red';                      //to make the input field's border in to reddish colour
                            return false;

                        } else {

                            document.getElementById('cust_name_error_msg_id').innerHTML = "";                           //since the condition is false the form gets submitted
                            document.getElementById('cust_name').style.border = "";

                        }

                    }

                </script>
</body>

</html>